USE [ATK];
GO

IF OBJECT_ID('mis.[Gold_Fact_CPD]', 'U') IS NOT NULL
    DROP TABLE mis.[Gold_Fact_CPD];
GO

CREATE TABLE mis.[Gold_Fact_CPD]
( 
    [Period]              DATETIME NULL,
    [ObjectType]          VARCHAR(36) NULL,
    [ObjectKind]          VARCHAR(36) NULL,
    [ObjectID]            VARCHAR(36) NULL,
    [ID]                  VARCHAR(36) NULL,
    [ConditionType]       NVARCHAR(256) NULL,
    [ConditionObjectType] VARCHAR(36) NULL,
    [ConditionObject_S]   NVARCHAR(600) NULL,
    [ConditionObject]     VARCHAR(36) NULL,
    [AdditionalInterest]  DECIMAL(4, 2) NULL,
    [DueDate]             DATETIME NULL,
    [ResponsibleID]       VARCHAR(36) NULL,
    [Responsible]         NVARCHAR(50) NULL,
    [IssueDate]           DATETIME NULL,
    [Completed]           VARCHAR(36) NULL,
    [CompletionDate]      DATETIME NULL,
    [Comment]             NVARCHAR(1000) NULL,
    [Verified]            VARCHAR(36) NULL,
    [IsAdditionalCondition]  VARCHAR(36) NULL,
    [Cancelled]           VARCHAR(36) NULL,
    [CreditRisk]          NVARCHAR(256) NULL,
    [LegalRisk]           NVARCHAR(256) NULL,
    [CommitteeApproved]   VARCHAR(36) NULL,
    [CollateralID]        VARCHAR(36) NULL,
    [Collateral]          NVARCHAR(150) NULL,
    [CancelledByID]       VARCHAR(36) NULL,
    [CancelledBy]         NVARCHAR(150) NULL,
    [VerifiedByID]        VARCHAR(36) NULL,
    [VerifiedBy]          NVARCHAR(150) NULL,
    [ModifiedDate]        DATETIME NULL,
    [SourceType]          VARCHAR(36) NULL,
    [SourceKind]          VARCHAR(36) NULL,
    [SourceID]            VARCHAR(36) NULL,
    [OwnerID]             VARCHAR(36) NULL,
    [Owner]               NVARCHAR(150) NULL
);
GO

INSERT INTO mis.[Gold_Fact_CPD]
(
    [Period],
    [ObjectType],
    [ObjectKind],
    [ObjectID],
    [ID],
    [ConditionType],
    [ConditionObjectType],
    [ConditionObject_S],
    [ConditionObject],
    [AdditionalInterest],
    [DueDate],
    [ResponsibleID],
    [Responsible],
    [IssueDate],
    [Completed],
    [CompletionDate],
    [Comment],
    [Verified],
    [IsAdditionalCondition],
    [Cancelled],
    [CreditRisk],
    [LegalRisk],
    [CommitteeApproved],
    [CollateralID],
    [Collateral],
    [CancelledByID],
    [CancelledBy],
    [VerifiedByID],
    [VerifiedBy],
    [ModifiedDate],
    [SourceType],
    [SourceKind],
    [SourceID],
    [OwnerID],
    [Owner]
)
SELECT
    [УсловияПослеВыдачиКредита Период],
    [УсловияПослеВыдачиКредита Объект Tип],
    [УсловияПослеВыдачиКредита Объект Вид],
    [УсловияПослеВыдачиКредита Объект ID],
    [УсловияПослеВыдачиКредита ИД],
    [УсловияПослеВыдачиКредита Тип Условия],
    [УсловияПослеВыдачиКредита Объект Условия Tип],
    [УсловияПослеВыдачиКредита Объект Условия _S],
    [УсловияПослеВыдачиКредита Объект Условия],
    [УсловияПослеВыдачиКредита Доп Проценты],
    [УсловияПослеВыдачиКредита Срок Выполнения],
    [УсловияПослеВыдачиКредита Исполнитель ID],
    [УсловияПослеВыдачиКредита Исполнитель],
    [УсловияПослеВыдачиКредита Дата Выдачи],
    [УсловияПослеВыдачиКредита Выполнено],
    [УсловияПослеВыдачиКредита Дата Выполнения],
    [УсловияПослеВыдачиКредита Комментарий],
    [УсловияПослеВыдачиКредита Проверено],
    [УсловияПослеВыдачиКредита Это Доп Условия],
    [УсловияПослеВыдачиКредита Аннулирован],
    [УсловияПослеВыдачиКредита Кредитный Риск],
    [УсловияПослеВыдачиКредита Юридический Риск],
    [УсловияПослеВыдачиКредита Одобренно Комитетом],
    [УсловияПослеВыдачиКредита Залог ID],
    [УсловияПослеВыдачиКредита Залог],
    [УсловияПослеВыдачиКредита Автор Аннулирования ID],
    [УсловияПослеВыдачиКредита Автор Аннулирования],
    [УсловияПослеВыдачиКредита Автор Проверки ID],
    [УсловияПослеВыдачиКредита Автор Проверки],
    [УсловияПослеВыдачиКредита Дата Изменения],
    [УсловияПослеВыдачиКредита Источник Tип],
    [УсловияПослеВыдачиКредита Источник Вид],
    [УсловияПослеВыдачиКредита Источник ID],
    [УсловияПослеВыдачиКредита Ответственный ID],
    [УсловияПослеВыдачиКредита Ответственный]
	
FROM [ATK].[dbo].[РегистрыСведений.УсловияПослеВыдачиКредита];