# Database connection
flyway.url=jdbc:sqlserver://MI-DEV-SQL01;databaseName=ATK;integratedSecurity=true
flyway.user=MICROINVEST\eugeniu.pascal

# Locations of SQL migration scripts
flyway.locations=filesystem:sql

# Optional settings
flyway.schemas=mis
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true
flyway.table=flyway_schema_history
